---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emqx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: emqx-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        EMQX_DASHBOARD__DEFAULT_USERNAME: "{{ .emqx_username }}"
        EMQX_DASHBOARD__DEFAULT_PASSWORD: "{{ .emqx_password }}"
  dataFrom:
    - extract:
        key: emqx
      rewrite:
        - regexp:
            source: "(.*)"
            target: "emqx_$1"

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emqx-init-user
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: emqx-init-user-secret
    template:
      engineVersion: v2
      data:
        init-user.json: |
          [
            {"user_id": "{{ index . "emqx_username" }}", "password": "{{ index . "emqx_password" }}", "is_superuser": true},
            {"user_id": "{{ index . "emqx_mqtt_username" }}", "password": "{{ index . "emqx_mqtt_password" }}", "is_superuser": false}
          ]
        init-acl: |
          {allow, {user, "{{ index . "emqx_mqtt_username" }}"}, all, ["#"]}.
  dataFrom:
    - extract:
        key: emqx
      rewrite:
        - regexp:
            source: "(.*)"
            target: "emqx_$1"
