---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: adguard-dns-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ADGUARD_URL: "{{ .adguard_url }}"
        ADGUARD_USER: "{{ .adguard_user }}"
        ADGUARD_PASSWORD: "{{ .adguard_password }}"
  dataFrom:
    - extract:
        key: adguard
      rewrite:
        - regexp:
            source: "(.*)"
            target: "adguard_$1"
